version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bosta_asses
      MYSQL_USER: osama
      MYSQL_PASSWORD: 1998
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db-data:
